### ISSUE TITLE
Deeply nested objects not being deserialized

### ISSUE THREAD

**Issue by steveh** [trailblazer/representable#197]
See this example:

https://gist.github.com/steveh/dec45cb0f4d1289848c473f84a13aae1

Say you have a tree of objects, Collection > Post > Category. If you deserialize Collection from JSON, the Category object is unavailable. If you derserialize Post, it is available.

Have I gone wrong somewhere, or is this a bug, or unsupported:

**Comment by apotonick** [comment]
Your structure is wrong, the `CollectionRepresenter` doesn't have any `category` property and hence doesn't know about this fragment. You would understand it better if you'd use `Decorator` instead of modules (highly recommended!). You will then see that the representer and the actual "models" (e.g. `Post) are completely unrelated.

Hit us up on https://gitter.im/trailblazer/chat if you need more help. :beers:
