### ISSUE TITLE
Will you drop Ruby 1.9, 2.0 support?

### ISSUE THREAD

**Issue by abinoam** [trailblazer/representable#208]
@myabc  and @apotonick the PR #207 failed on travis because of Nokogiri.

With the message:
```nokogiri-1.7.0.1 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p598```

See: https://travis-ci.org/trailblazer/representable/jobs/192645510

Will you drop support for Ruby 1.9 and 2.0?
* 1.9 has died 2015-02-23
* 2.0 has died 2016-02-24
* 2.1 had its last release on 2016-03-30 and will probably officially die next month

Source: 
- https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/
- https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
- https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/

**Comment by abinoam** [comment]
Just saw this comment from @myabc at PR #205  https://github.com/trailblazer/representable/pull/205/files#r92008255. Linking it here as are related.

**Comment by abinoam** [comment]
We always may manage multiple Gemfile versions.
https://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-versions-of-dependencies

**Comment by apotonick** [comment]
We will continue Ruby 1.9. The fact they have stopped doesn' meant there are thousands and tenthousands of apps out there that don't need our gems for upgrading!!!!!!

**Comment by myabc** [comment]
@abinoam I've encountered the Bundler nokogiri resolution error on 1.9.3 - my workaround was to specify an older version of nokogiri: https://github.com/trailblazer/roar/commit/b4c2cbf658e24ad0962e2fd348925492fe4beee9

According to [this thread](https://github.com/bundler/bundler-features/issues/95#issuecomment-234403344), it should have been fixed in Bundler 1.13.

**Comment by myabc** [comment]
@abinoam #205 is actually still pending because it would break 1.9.3 support!

**Comment by solnic** [comment]
Heh we actually dropped support for ruby < 2.2.0 in dry/rom. I think it's a big mistake to support ancient rubies, trailblazer just like rom/dry/hanami is a niche project, it's gonna take years until it's used by many people and spending that time so that MAYBE some folks will use it in their app running on mri 1.9 is basically a waste of time. It's also worth to notice that IF somebody is running an app on an ancient ruby then upgrading to recent ruby is more important than introducing new gems in the stack. I believe we're building gems for future rubies, gems that will shine on rubies like mri 3.0 or jruby or even truffleruby, and investing a significant amount of time just to support something as old as mri 1.9 will slow down the progress.

Anyhow, just my 2 cents :)

**Comment by apotonick** [comment]
There are many projects where the TRB gems are in use in 1.9 and help upgrading people, since the gems allow decouple code from Rails (which is usually why they can't upgrade). The whole TRB idea is to help people upgrade, and since I know it actually happens, I'm happy to spend a tiny wee bit of time on 1.9.

Nevertheless, I agree with @solnic that we shouldn't waste too much time. I personally make use of "all the great Ruby 2.x features" (which are..... .... ..... ah, keyword arguments!) :laughing: and try to leverage them wherever I can, but since Ruby hasn't introduced *anything* valuable in terms of language constructs or architecture (no, adding methods to `Enumerable` does *not* help me write better software), I don't see why I should restrict the gem. I don't think it will "encourage" people to stay on 1.9.

**Comment by apotonick** [comment]
What's truffleruby?

**Comment by myabc** [comment]
@apotonick fork of JRuby https://github.com/graalvm/truffleruby

**Comment by abinoam** [comment]
I completely agree with @solnic!
But...  I understand @apotonick!

Thanks @myabc for the fix to the Gemfile!
